export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS
export const WEB3MODAL_PROJECT_ID = process.env.NEXT_PUBLIC_WEB3MODAL_PROJECT_ID
export const NETWORK_CHAIN_ID = process.env.NEXT_PUBLIC_NETWORK_CHAIN_ID
export const NETWORK_NAME = process.env.NEXT_PUBLIC_NETWORK_NAME
export const NETWORK_RPC_URL = process.env.NEXT_PUBLIC_NETWORK_RPC_URL
export const NETWORK_EXPLORER = process.env.NEXT_PUBLIC_NETWORK_EXPLORER
export const NETWORK_CURRENCY = process.env.NEXT_PUBLIC_NETWORK_CURRENCY
